trade_goods = {
        "11": "Common Electronics",
        "12": "Common Industrial Goods",
        "13": "Commom Manufactured Goods",
        "14": "Common Raw Materials",
        "15": "Common Consumables",
        "16": "Common Ore",
        "21": "Advanced Electronics",
        "22": "Advanced Machine Parts",
        "23": "Advanced Manufactured Goods",
        "24": "Advanced Weapons",
        "25": "Advanced Vehicles",
        "26": "Biochemicals",
        "31": "Crystals and Gems",
        "32": "Cybernetics",
        "33": "Live Animals",
        "34": "Luxury Consumables",
        "35": "Luxury Goods",
        "36": "Medical Supplies",
        "41": "Petrochemicals",
        "42": "Pharmaceuticals",
        "43": "Polymers",
        "44": "Precious Metals",
        "45": "Radioactives",
        "46": "Robots",
        "51": "Spices",
        "52": "Textiles",
        "53": "Uncommon Ore",
        "54": "Uncommon Raw Materials",
        "55": "Lumber",
        "56": "Vehicles",
        "61": "Illegal biochemicals",
        "62": "Illegal cybernetics",
        "63": "Illegal drugs",
        "64": "Illegal luxuries",
        "65": "Illegal weapons",
        "66": "Exotics"
}

trade_codes = {
    "Ag": ["26", "33", "34", "52 ],
    "As": ["31", "44", "45"],
    "Ba": [],
    "De": ["31", "41", "44", "45", "51"],
    "Fl": ["41", "44"],
    "Ga": ["33", "34", "51"],
    "Hi": ["35", "36"],
    "Ht": ["21", "22", "23", "24", "25", "32", "36"],
    "Ie": ["31", "41"],
    "In": ["21", "22", "23", "24", "25", "43", "46"],
    "Lo": ["45"],
    "Lt": [],
    "Na": [],
    "Ni": ["52"],
    "Po": [],
    "Ri": [],
    "Va": [],
    "Wa": ["26", "34", "41", "51"]
}